{% set data=load_setup_py_data() %}

package:
  name: ngs_utils
  version: {{ data.version }}

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python >=3.7
    - numpy
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python >=3.7
    {% for dep in data.install_requires -%}
    - {{ dep.lower() }}
    {% endfor %}
    # All dependencies are optional, depending on functionality you'd want:
    # - bedtools>=2.25
    # - sambamba
    # - htslib
    # - cython
    # - numpy
    # - pysam
    # - pybedtools
    # - gffutils                # for generating regions through GFF file
    # - pyyaml                  # for Bcbio parsing
    # - natsort                 # for Sample calss and Bcbio parsing
    # - joblib                  # for parallelization
    # - ipython-cluster-helper  # for parallelization
    # - lxml                    # for html2base64
    # - beautifulsoup4          # for html2base64

test:
  imports:
    - ngs_utils.file_utils
    - ngs_utils.reference_data

about:
  home: "{{ data.url }}"
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  summary: "{{ data.description }}"
