{% set version = "5.2.2vlad" %}

package:
  name: snakemake
  version: {{ version }}

source:
  git_url: https://bitbucket.org/vladsaveliev/snakemake
  git_rev: master

build:
  number: 0
  skip: True # [py27]
  script: python -m pip install --no-deps --ignore-installed .
#  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - snakemake = snakemake:main
    - snakemake-bash-completion = snakemake:bash_completion

requirements:
  build:
    - python
    - pip
    - setuptools
    - wrapt
    - requests
    - ratelimiter
    - configargparse
    - appdirs
    - datrie
  run:
    - python
    - wrapt
    - requests
    - docutils
    - pyyaml
    - datrie
    - requests >=2.8.1
    - psutil
    - ratelimiter
    - configargparse
    - appdirs
    - jsonschema

test:
    imports:
      - snakemake
    commands:
      - snakemake --version

about:
  home: https://snakemake.readthedocs.io
  license: MIT
  summary: Snakemake is a workflow management system that aims to reduce the complexity of creating workflows by providing a fast and comfortable execution environment, together with a clean and modern specification language in python style. Snakemake workflows are essentially Python scripts extended by declarative code to define rules. Rules describe how to create output files from input files.
